name: Setup PHP

description: Setup PHP build

inputs:
    php-version:
        description: 'PHP version to use, default to 8.1'
        required: false
        default: '8.2'

runs:
    using: composite
    steps:
        -   name: Install PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: ${{ inputs.php-version }}

        -   id: install-composer-dependencies
            name: Install composer dependencies
            run: make vendor
            shell: bash
